### ISSUE TITLE
Cannot display static context on Linux

### ISSUE THREAD

**Issue by restagner** [javaConductor/gserv#27]
I'm using gserv on Linux and when I run the following command

```shell
gserv -s /home/restagner/public -p 64000
```

and then navigate to the following url in my browser 

```text
http://localhost:64000/public/index.html
```

I see

```text
No such resource: /public/index.html
```

What am I doing wrong?

**Comment by javaConductor** [comment]
"-s /home/restagner/public" says that resources are relative to THIS folder.  You can refer to the html file as just  "/index.html"  because /home/restagner/public directly contains the file.  
 
Lee

**Comment by restagner** [comment]
@javaConductor 

Thanks.  That was it!!
